### ISSUE TITLE
Remove build files from repository

### ISSUE THREAD

**Issue by johndjameson** [drewbarontini/baseman#3]
The `build` directory is listed in `.gitignore`, but we still track some files in the [repository][baseman-build].

```text
build/
bin/
.bundle/
.sass-cache/
.DS_Store
.cache
bower_components
node_modules
```

Should we delete the files from Baseman or update our `.gitignore`?

[baseman-build]: https://github.com/drewbarontini/baseman/tree/master/build

cc @drewbarontini

**Comment by drewbarontini** [comment]
Nice catch! They're gone.
